spring.application.name=demoEcommmerce
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=${JWT_SECRET}
server.port=${PORT:8080}

https://railway.com/project/c7b6aec3-9126-4e1c-8f79-eceb2aa3c1f8?environmentId=fe414e21-0136-4294-8c04-7041d7a4fe92